name: AZ cli

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: 'Select env:- dev/qa/prod'
        required: true
        options:
        - dev
        - qa
         
permissions:
      id-token: write
      contents: read        

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: '${{ github.event.inputs.environment }}'
    env:
      ENV: '${{ github.event.inputs.environment }}'
      RG: 'RG-${{ github.event.inputs.environment }}'

    steps:

    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v2

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{secrets.Azure_Login}}

    - name: Azure CLI Action
      uses: Azure/cli@v1.0.9
      with:
        azcliversion: 2.37.0
        inlineScript: |
            az group list --output table	
                    
