name: AZ cli

on:
  push

         
permissions:
      id-token: write
      contents: read        

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    env:
      RG: 'RG-dev'

    steps:

    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v2

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{secrets.Azure_Login}}

    - name: Azure CLI Action
      uses: Azure/cli@v1.0.9
      with:
        azcliversion: 2.37.0
        inlineScript: |
            az group list --output table	
                    
