name: Appservice

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: 'Select env:- dev/qa/prod'
        required: true
        options:
        - dev
        - qa
        - prod  
      AppService:
        type: choice
        description: 'Select app service to deploy'
        required: true
        options:
        - Appservice
        - windows-Appservice

permissions:
      id-token: write
      contents: read        

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      ENV: '${{ github.event.inputs.environment }}'
      RG: 'AppService-${{ github.event.inputs.environment }}'

    steps:

    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v2

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{secrets.Azure_Login}}
       

    - name: Deploy Bicep template
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        resourceGroupName: ${{ env.RG }}
        template: ${{ github.event.inputs.AppService}}.bicep
        parameters: ${{ github.event.inputs.AppService}}-${{ env.ENV }}.parameters.json           
           
