name: Appservice

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: 'Select env:- dev/qa/prod'
        required: true
        options:
        - dev
        - qa
        - prod  
      AppService:
        type: choice
        description: 'Select app service to deploy'
        required: true
        options:
        - Appservice
        - windows-Appservice

permissions:
      id-token: write
      contents: read        

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      ENV: '${{ github.event.inputs.environment }}'
      RG: 'AppService-${{ github.event.inputs.environment }}'

    steps:

    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v2

  
    - name: Install Azure cli
      run: |
          sudo apt-get install ca-certificates curl apt-transport-https lsb-release gnupg
          curl -sL https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/microsoft.gpg > /dev/null
          AZ_REPO=$(lsb_release -cs)
          echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ $AZ_REPO main" | sudo tee /etc/apt/sources.list.d/azure-cli.list
          sudo apt-get update
          sudo apt-get install azure-cli

#Install powershell
    - name: Install powershell
      run: |
          wget -q https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb
          sudo dpkg -i packages-microsoft-prod.deb
          sudo apt-get update
          sudo add-apt-repository universe
          sudo apt-get install -y powershell
          pwsh      

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: Azure_Login

    - name: Azure CLI
      uses: azure/CLI@v1
      with:
        azcliversion: 2.37.0
        inlineScript: |
            az account list --output table	          


    - name: Deploy Bicep template
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        resourceGroupName: ${{ env.RG }}
        template: ./${{ env.AppService }}.json
        parameters: ./${{ env.AppService }}-${{ env.ENV }}.parameters.json           
           
